### PR TITLE
Adapt to the latest master branch

### PR DESCRIPTION
**Pull request by kuscsik**
Tested with the latest  Chromium master branch on an ARMv8 build with Mesa and Wayland 1.9.

### CODE REVIEW

**Comment by kalyankondapally** [comment]
LGTM
@joone ping

**Comment by joone** [comment]
@kuscsik  what latest commit of Chromium did you test with your changes?

**Comment by kalyankondapally** [comment]
@joone Thanks 
@kuscsik You need to update chromium revision here https://github.com/01org/ozone-wayland/blob/master/.DEPS.git

**Comment by kuscsik** [comment]
@joone @kalyankondapally Updated the .DEPS.git file as requested.

**Comment by kalyankondapally** [comment]
For some reason, keyboard input seems to be broken.  

[6155:6155:1104/102321:ERROR:xkb_keyboard_layout_engine.cc(845)] No current XKB state
[6155:6155:1104/102321:ERROR:xkb_keyboard_layout_engine.cc(845)] No current XKB state
[6155:6155:1104/102321:ERROR:xkb_keyboard_layout_engine.cc(845)] No current XKB state
[6155:6155:1104/102321:ERROR:xkb_keyboard_layout_engine.cc(845)] No current XKB state
[6155:6155:1104/102322:ERROR:xkb_keyboard_layout_engine.cc(845)] No current XKB state
[6155:6155:1104/102322:ERROR:xkb_keyboard_layout_engine.cc(845)] No current XKB state
[6155:6155:1104/102322:ERROR:xkb_keyboard_layout_engine.cc(845)] No current XKB state

**Comment by kuscsik** [comment]
I tested the patch set only with a mouse. I can reproduce the issue with
Mesa 11.
Seem like an issue with the XKB initialisation.

Z

**Comment by joone** [comment]
I saw the same keyboard problem.

**Comment by joone** [comment]
I submitted a patch to fix the keyboard problem.

**Comment by kalyankondapally** [comment]
Merged

**Pull request closed without merging**
