### PR TITLE
Add support for receiving drag-and-drop data from other processes

### PR DESCRIPTION
**Pull request by mcatanzaro**
Here's initial support for drag-and-drop, fixing #134. This is still a WIP. Note that this is the IPC sort of drag-and-drop (the Wayland replacement for ICCCM); dragging the Chrome window around is an unrelated problem.

What works:

 * Dragging text into Chrome.
 * Dragging files into Chrome.

Demos: https://people.gnome.org/~mcatanzaro/ozone-wayland/

Caveats (this list is a bit long, but I figure it's better to post the pull request early for feedback):

 * Drags out of Chrome are not yet supported, only drags into Chrome. So you can't (yet) e.g. drag a tab from one window to another. This will be implemented in a separate pull request.
 * ~~There is some vertical offset bug I haven't figured out, so you have to drop things a good distance above the target for it to work.~~ Fixed thanks to your help.
 * ~~Drags from GTK+ apps seem to be artificially completed too soon, so it's hard to test them (you have to move quickly). I think this is more likely a GTK+ bug than a problem in my code, but I haven't tracked it down yet.~~ This is caused by [Wayland bug #91944](https://bugs.freedesktop.org/show_bug.cgi?id=91944). No changes in Ozone-Wayland are required.
 * ~~Sometimes the GPU process crashes after receiving a file. Probably a bug in my code.~~ Fixed this a while ago, somehow.
 * ~~In the Imgur demo, I have to drop the file twice before imgur notices it (not sure why).~~ This has also been fixed for a while, somehow.
 * After dragging a file, the web site does not actually have permission to open it (so e.g. in the Imgur example, Imgur knows what the file is, but the upload won't work). This is still broken.
 * ~~The GPU process crashes in `WaylandDataOffer::Receive` when dragging a flower in and out of the window rapidly. This still occurs. The problem is that data_offer_ is somehow invalid.~~ Fixed, it was a bug in my code.
 * ~~There are a couple TODOs left in the code for me to fix.~~ The remaining TODOs are minor enhancements.

Bonus: This includes a bit of plumbing needed for clipboard (copy/paste), which is a related problem.

### CODE REVIEW

**Comment by kalyankondapally** [comment]
Sorry, for the delay. Will have a look today and give you feedback

**Comment by mcatanzaro** [comment]
As a warning, the last commit breaks drag-and-drop somehow; that's why I hadn't asked for another review yet.

**Comment by kalyankondapally** [comment]
ha Sorry for the noise.

**Comment by mcatanzaro** [comment]
OK, I think I've responded to all your comments now (note the last commit about ownership of the WaylandDataOffer) and have basic dnd working again to the extent advertised in the first post. I still have to deal with that original to-do list. "Sometimes the GPU process crashes after receiving a file" seems to be worse than before.

**Comment by kalyankondapally** [comment]
If the crashes are in gpu process side, you can debug it this way:
chrome --no-sandbox --gpu-launcher='xterm -title renderer -e gdb --eval-command=run --args' 
Or is it in Browser or Render Process side ?

**Comment by kalyankondapally** [comment]
I am running weston on my ubuntu machine, any easy way to try this ?

**Comment by mcatanzaro** [comment]
Any particular problem you're running into?

To get the nice weston-dnd demo client, you need to configure Weston with --enable-demo-clients-install. I need to change the O-W jhbuild moduleset to do this.

To test with GTK+ applications... might not be easy on Ubuntu. Thinking a bit about this, I think the best option would be for me to try adding GTK+ as an optional module (not built by default) to O-W's jhbuild, then you can 'jhbuild build gtk+', and then in theory you can launch GTK+ apps from Unity and they will appear in Weston, or simply from weston-terminal. In theory. I've been using GNOME's jhbuild; what I do is 'jhbuild run weston --fullscreen' then Alt+Tab back to GNOME Shell and launch any GTK+ app from there (it appears in Weston). My warning that the code is unreliable for drags from GTK+ apps still applies :( so maybe you can test with weston-dnd and see it work better instead. :p

I haven't tested with Qt yet.

**Comment by kalyankondapally** [comment]
K, I will try to set it up. No, I was just curious to see it in action before going further with review.

**Comment by kalyankondapally** [comment]
I have built weston examples and given this a try. It crashes when you dont have a target where you can drop things. It was related to uninitialized raw pointers, added my comments which need to be fixed. I will go through the code tomorrow and do the review.

**Comment by mcatanzaro** [comment]
Oooops :(

Yes, my work is based on DesktopDragDropClientAuraX11. I have a bit of an advantage in that DnD is much simpler in Wayland!

**Comment by kalyankondapally** [comment]
Once we have nailed down the basic architecture and flow, can you write a short doc explaining it and I will merge it  https://docs.google.com/document/d/118Cmq_dedHOr4jfyVeE4jBhV7hXzhnaVCqegNMGano0/edit#heading=h.hfcsgc1srzd1 ?

**Comment by mcatanzaro** [comment]
OK, I think I've addressed all your review comments. I found one more crash that needs fixed (added info about it to the to-do list in the first post). I also still need to update the Google Doc.

**Comment by joone** [comment]
@mcatanzaro do you any jhbuild module file for building weston and gtk+ together?

**Comment by kalyankondapally** [comment]
thx, gone through the changed versions and new patches. We are getting there. I have left few comments to this file : https://github.com/mcatanzaro/ozone-wayland/commit/af83e458036624532d49285365d6b9a0574f94b8

I think once we have addressed them and the new crash, we can get this initial series merged while you work on it.

**Comment by mcatanzaro** [comment]
"do you any jhbuild module file for building weston and gtk+ together?"

TBH I have been using GNOME jhbuild with the following configuration:

```
moduleset = 'gnome-world'
modules = ['meta-gnome-core', 'meta-gnome-apps-tested']

module_autogenargs = {
    'weston': '--enable-demo-clients-install'
}
```

I know that's not a good answer, so I will try to add GTK+ to the Ozone-Wayland jhbuild environment, to make it easier to build for non-GNOME folks.

**Comment by kalyankondapally** [comment]
@mcatanzaro Unfortunately, things have changed a bit in master and you would  need to re base these patches.

**Comment by mcatanzaro** [comment]
Sorry for my delay. I will try to rebase this soon, update the jhbuild moduleset, and also figure out what is going on with those GPU process crashes I've introduced.

**Comment by mcatanzaro** [comment]
Apologies again for the delay on this! I still do intend to rebase this and also to implement drags out of Chrome but it will be a couple more weeks, sorry.

**Comment by mcatanzaro** [comment]
OK, this has been "rebased." Actually it was rather hard to do a rebase with so many changes in master, so I did a merge instead. Depending on your preference, you can take this:

* All in one commit (as in this updated merge request)
* With commit history preserved, but it's rather messy, with two huge merge commits, at https://github.com/mcatanzaro/ozone-wayland/commits/dnd_merge

There is one serious regression from the rebase that I am currently trying to fix: the coordinate offset bug has returned, and it's much worse than before; drops must occur far to the right and below the intended target. I am looking at the code around ConvertPointFromNativeScreen/ConvertPointToHost/ConvertPointToTarget to see if anything looks suspicious there.

**Comment by mcatanzaro** [comment]
I notice that the window menu in the top-right now opens far below the correct position. I expect that is related to my coordinate offset bug. I also notice that `DesktopWindowTreeHostOzone` now overrides `GetRootTransform`, which is used in translating between coordinate systems. But tbh, I don't understand the code, and removing the override doesn't fix the problem.

**Comment by kalyankondapally** [comment]
Ya seems bit broken. I will take a look into this later, should be in  master only though. Can you create an issue about the positioning bug ? 
 Also, under src/ozone can you run tools/check-coding-style.sh and check the issues being reported.

**Comment by mcatanzaro** [comment]
Um, I can't reproduce the positioning bug with the window menu anymore. I wonder if I broke it myself by changing code locally, and forgot; not sure.

I'll fix the style issues.

**Comment by mcatanzaro** [comment]
I can't reproduce the drag offset bug anymore either; it's working fine for me now. Hm....

**Comment by kalyankondapally** [comment]
K thanks for checking, let me know when you think these patches are ready for review

**Comment by mcatanzaro** [comment]
Hi, they're ready now!

**Comment by kalyankondapally** [comment]
I couldn't go through this change yet, will check them out in a day or two.

**Comment by mcatanzaro** [comment]
Thanks for the review. I rebased and got rid of the problematic `delayed_drop_target_event_`.

**Comment by kalyankondapally** [comment]
Thx merged.

**Pull request closed without merging**
