### PR TITLE
M45 gardening

### PR DESCRIPTION
**Pull request by mrunalk**
Probably we need to create new branch for M45 but creating this PR for Milestone-Jefferson for now.

### CODE REVIEW

**Comment by rakuco** [comment]
There's a ticket for M45: #402.
We normally branch from master, not from the previous release branch, as we want the new features that were developed in the meantime, and master is generally kept more up to date with Chromium's bleeding edge.

Can you check master and see if there's any gardening that needs to be done there?

**Comment by mrunalk** [comment]
Ahh... I will check the master and submit different PR if required. Thanks.

**Comment by kalyankondapally** [comment]
Can this be closed ?

**Comment by mrunalk** [comment]
Done

**Pull request closed without merging**
