### PR TITLE
Build fixes for M43 rebase

### PR DESCRIPTION
**Pull request by mrunalk**
1. Change from DRI to DRM as per Cr upstream.
2. Add OzoneWebUI::UpdateDeviceScaleFactor
3. Update kThreadPriority_Background to ThreadPriority::Background

### CODE REVIEW

**Comment by mrunalk** [comment]
@joone @kalyankondapally can you take a look now?

**Comment by kalyankondapally** [comment]
The changes look ok, however we are having some issues with HWA Video with chromium master TOT. We need to resolve that before we can update OZ-WL latest master. Did you try building with HWA Video support enabled

**Comment by kalyankondapally** [comment]
I have atleast committed part of your changes to Milestone-Hood branch

**Comment by mrunalk** [comment]
@kalyankondapally, sorry I didn't look at the commit history earlier. I think all the changes are there so I will close this PR.

**Pull request closed without merging**
