### PR TITLE
First round of fixes for M43 rebase

### PR DESCRIPTION
**Pull request by mrunalk**

### CODE REVIEW

**Comment by rakuco** [comment]
Could you please be more specific? Right now, oz-wl is still targeting M42 mostly because nobody has worked on moving it to a more recent Chromium version. Moving to a more recent version usually involves:

* Updating the Chromium hash in `.DEPS.git`
* Providing separate commits adapting the code for each Chromium CL that requires a change in oz-wl.

**Comment by kalyankondapally** [comment]
We are in the process of updating OZ-WL to latest Chromium master tip and doing a  M43 based release, I will re-use the work from here.

**Comment by mrunalk** [comment]
@rakuco sorry for the late reply. Can we create separate branch for M43/next then? Otherwise Ozone-Wayland build will be broken for next release.

**Comment by kalyankondapally** [comment]
@mrunalk https://github.com/01org/ozone-wayland/issues/373 
Here you can track the release branch

**Comment by mrunalk** [comment]
Closing this and opening new one for Milestone-Hood here, https://github.com/01org/ozone-wayland/pull/376

**Pull request closed without merging**
